"""
Reference Resolution Engine.

Responsible for:

- Scope construction
- Identifier resolution
- Symbol references
- Name lookup
- Semantic navigation

This package intentionally contains no parsing logic.
It operates purely on semantic data generated by the
Document and Symbol extraction stages.
"""

from .models import (
    Reference,
    ReferenceKind,
)

from .scope import Scope